<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */

namespace APIMATICCalculatorLib\Models;

use APIMATICCalculatorLib\Models\BaseEnum;

class OperationTypeEnum extends BaseEnum {
    /**
     * Represents the sum operator
     */
    const SUM = "SUM";

    /**
     * Represents the subtract operator
     */
    const SUBTRACT = "SUBTRACT";

    /**
     * Represents the multiply operator
     */
    const MULTIPLY = "MULTIPLY";

    /**
     * Represents the divide operator
     */
    const DIVIDE = "DIVIDE";

}