<?php
/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */

namespace APIMATICCalculatorLib;

class Configuration {
    //The base Uri for API calls
    public static $BASEURI = 'https://examples.apimatic.io/apps/calculator';

}
